server:
  port: 10001

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false 
    
security:
  basic:
     enabled: true
  user:
    name: admin
    password: 198377