eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:198377@localhost:10001/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
server:
  port: 10002
spring:
  application:
    name: service-hi-1
