eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:198377@localhost:10001/eureka/
server:
  port: 10006
spring:
  application:
    name: service-feign
feign:
   hystrix:
     enabled: true